# Generated by Django 6.1 on 2026-08-29 05:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text='HR-assigned identifier, e.g. EMP-00001', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('job_title', models.CharField(max_length=150)),
                ('country', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('currency', models.CharField(help_text='ISO 4217 currency code', max_length=3)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Annual gross salary in local currency', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('salary_effective_date', models.DateField(help_text='Date when the current salary became effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='idx_employee_name')],
            },
        ),
    ]
